### ISSUE TITLE
[issue] HF_MSDSAL mode 

### ISSUE THREAD

**Issue by cabiamdos** [salmg/NFCopy#3]
Hello

I know this isn't the correct repository, but I don't know where is your contact info.
I am having problems with HF_MSDSAL mode in proxmark3.

Here is the video of the output, it enters in a infinite loop and it never ends up emulating the card.
https://vimeo.com/659974338

I was wondering, why I a having this issue?
I have installed the client in a raspberry pi, in a pc (with proxspace), and without proxspace with a pre-compiled build. Also I have tried installing proxmark from your own repository (https://github.com/salmg/proxmark3) and I have got the same bug.

Any help is very appreciated
My contacts, telegram @cabiam and email cabiam@criptext.com

Thanks
merry christmas

**Comment by salmg** [comment]
The MSDSAL mode works on Visa cards, and you are using a MasterCard card
